# Generated by Django 2.1.1 on 2018-10-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_provider',
            field=models.BooleanField(default=False, verbose_name='is_provider'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_visitor',
            field=models.BooleanField(default=False, verbose_name='is_visitor'),
        ),
    ]
