# Generated by Django 2.1.1 on 2018-10-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_availability', models.BooleanField(default=True)),
                ('availability_30', models.PositiveSmallIntegerField(default=30)),
                ('availability_60', models.PositiveSmallIntegerField(default=60)),
                ('availability_90', models.PositiveSmallIntegerField(default=90)),
                ('availability_365', models.PositiveSmallIntegerField(default=365)),
                ('number_of_reviews', models.PositiveSmallIntegerField(default=0)),
                ('first_review', models.DateField(null=True)),
                ('last_review', models.DateField(null=True)),
                ('review_rating', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('property_type', models.CharField(default='', max_length=63)),
                ('square_feet', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('room_type', models.CharField(default='', max_length=63)),
                ('is_dedicated', models.BooleanField(default=False)),
                ('accomodates', models.PositiveSmallIntegerField(default=1)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('beds', models.PositiveSmallIntegerField(default=1)),
                ('bed_type', models.CharField(max_length=31, null=True)),
                ('bathrooms', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('street', models.CharField(default='', max_length=63)),
                ('unit', models.CharField(max_length=63, null=True)),
                ('city', models.CharField(default='', max_length=63)),
                ('state', models.CharField(default='', max_length=63)),
                ('zipcode', models.CharField(default='', max_length=63)),
                ('amenities', models.CharField(max_length=2047, null=True)),
                ('access', models.CharField(max_length=1023, null=True)),
                ('picture_url', models.CharField(default='', max_length=255)),
                ('summary', models.CharField(default='', max_length=1023)),
                ('description', models.CharField(max_length=1023, null=True)),
                ('notes', models.CharField(max_length=1023, null=True)),
                ('neighbourhood_overview', models.CharField(max_length=1023, null=True)),
                ('transit', models.CharField(max_length=1023, null=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('requirements', models.CharField(max_length=255, null=True)),
                ('cancellation_policy', models.CharField(default='', max_length=63)),
                ('house_rules', models.CharField(default='', max_length=1023)),
                ('advance_notice', models.CharField(default='', max_length=15)),
                ('check_in_from', models.CharField(default='', max_length=7)),
                ('check_in_to', models.CharField(default='', max_length=7)),
                ('advance_booking', models.CharField(default='', max_length=31)),
                ('minimum_nights', models.PositiveSmallIntegerField()),
                ('maximum_nights', models.PositiveSmallIntegerField()),
                ('instant_bookable', models.BooleanField(default=False)),
                ('daily_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('special_offer', models.BooleanField(default=False)),
                ('weekly_price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('extra_people', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
            ],
        ),
    ]
