# Generated by Django 2.1.1 on 2018-10-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_listing_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='accomodates',
            new_name='accommodates',
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
