# Generated by Django 2.1.1 on 2018-10-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_auto_20181003_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='house_rules',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
