# Generated by Django 2.1.1 on 2018-10-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0004_auto_20181003_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='advance_booking',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='advance_notice',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='check_in_from',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='check_in_to',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
