# Generated by Django 2.1.1 on 2018-10-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0005_auto_20181003_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='summary',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
