# Generated by Django 2.1.1 on 2018-10-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0007_auto_20181003_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='beds',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
