# Generated by Django 2.1.1 on 2018-10-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0009_auto_20181003_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
