# Generated by Django 2.1.1 on 2018-10-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0011_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='days',
            field=models.PositiveIntegerField(),
        ),
    ]
