# Generated by Django 2.1.1 on 2018-10-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0012_auto_20181007_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='days',
            field=models.CharField(max_length=31),
        ),
    ]
