# Generated by Django 2.1.1 on 2018-10-01 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('submitted_on', models.DateTimeField(default=datetime.datetime.now)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023, null=True)),
                ('neighbourhood', models.CharField(max_length=63)),
                ('city', models.CharField(max_length=63)),
                ('state', models.CharField(max_length=63)),
                ('property_type', models.CharField(max_length=63, null=True)),
                ('room_type', models.CharField(max_length=63, null=True)),
                ('accomodates', models.PositiveSmallIntegerField()),
                ('bathrooms', models.PositiveSmallIntegerField(null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(null=True)),
                ('beds', models.PositiveSmallIntegerField(null=True)),
                ('bed_type', models.CharField(max_length=31, null=True)),
                ('amenities', models.CharField(max_length=2047, null=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
            ],
        ),
    ]
