# Generated by Django 2.1.1 on 2018-10-02 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20181001_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='access',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='accomodates',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='bathrooms',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='request',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='beds',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='check_in',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='request',
            name='check_out',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='request',
            name='city',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='request',
            name='neighbourhood',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='request',
            name='property_type',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='request',
            name='room_type',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
