# Generated by Django 2.1.1 on 2018-10-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20181015_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='accomodates',
            new_name='accommodates',
        ),
    ]
